platform :ios, '13.0'

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  # Подключаем Flutter-плагины вручную (если знаешь, какие нужны),
  # либо просто не вызывай flutter_install_all_ios_pods (но тогда плагины не подтянутся автоматически)
end
