# Поддерживаемая версия iOS
platform :ios, '13.0'

# Путь до Flutter SDK
ENV['FLUTTER_ROOT'] ||= File.expand_path('~/flutter')

require_relative '../.flutter-plugins-dependencies'

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

